[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# nerdtree
repo = 'scrooloose/nerdtree'

[[plugins]]
# Ememt
repo = 'mattn/emmet-vim'

[[plugins]]
# ステータスバー
repo = 'itchyny/lightline.vim'

[[plugins]]
# インデントガイド
repo = 'nathanaelkane/vim-indent-guides'
