#!/bin/bash

function createDirectory() {
  if [ ! -d $1 ];
  then
    mkdir -p $1
  fi
}

function findAndCp() {
    find "$1" -maxdepth 1 | awk 'NR!=1' | xargs -i cp -r {} "$2"
}

VIM_HOME="${HOME}/.vim"
BUNDLES_DIR="${VIM_HOME}/bundles"
COLORS_DIR="${VIM_HOME}/colors"
AUTOLOAD_DIR="${VIM_HOME}/autoload"
SRC_DIR="${VIM_HOME}/src"
THEME_DIR="${VIM_HOME}/themes"

dirctries=("${VIM_HOME}" "${BUNDLES_DIR}" "${COLORS_DIR}" "${AUTOLOAD_DIR}" "${SRC_DIR}" "${THEME_DIR}")

# Create Directories
for dir in ${dirctries[@]};
do
  createDirectory $dir
done

cd "${HOME}"

curl -s https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > "${HOME}/installer.sh"

sh "${HOME}/installer.sh" "${BUNDLES_DIR}"

rm -rf "${HOME}/installer.sh"

# Install colorscheme
COLOR_REPOS=("https://github.com/cocopon/iceberg.vim.git" "https://github.com/sheerun/vim-wombat-scheme.git")

cd "${THEME_DIR}"

for repo in ${COLOR_REPOS[@]};
do
  git clone $repo >/dev/null 2>&1
done

for item in `ls ${THEME_DIR} | awk '{print $1}'`;
do
  THEME_COLOR_DIR="${THEME_DIR}/${item}/colors"
  THEME_SRC_DIR="${THEME_DIR}/${item}/src"
  THEME_AUTOLOAD_DIR="${THEME_DIR}/${item}/autoload"

  if [ -d "${THEME_COLOR_DIR}" ];
  then
    findAndCp "${THEME_COLOR_DIR}" "${COLORS_DIR}"
  fi

  if [ -d "${THEME_SRC_DIR}" ];
  then
    findAndCp "${THEME_SRC_DIR}" "${SRC_DIR}"
  fi

  if [ -d "${THEME_AUTOLOAD_DIR}" ];
  then
    findAndCp "${THEME_AUTOLOAD_DIR}" "${AUTOLOAD_DIR}"
  fi
done

cp .vimrc "${HOME}/.vimrc"
