#!/bin/bash

function createDirectory() {
  if [ ! -d $1 ];
  then
    mkdir -p $1
  fi
}

function findAndCp() {
    find "$1" -maxdepth 1 | awk 'NR!=1' | xargs -i cp -r {} "$2"
}

ROOT_DIR=$(cd $(dirname $0); pwd)

VIM_HOME="${HOME}/.vim"
CONFIG_HOME="${HOME}/.config/vim"
BUNDLES_DIR="${CONFIG_HOME}/bundles"
COLORS_DIR="${CONFIG_HOME}/colors"
AUTOLOAD_DIR="${CONFIG_HOME}/autoload"
SRC_DIR="${CONFIG_HOME}/src"
THEME_DIR="${CONFIG_HOME}/themes"

: "Create directories" && {
  dirctries=("${CONFIG_HOME}" "${BUNDLES_DIR}" "${COLORS_DIR}" "${AUTOLOAD_DIR}" "${SRC_DIR}" "${THEME_DIR}" "${VIM_HOME}")

  for dir in ${dirctries[@]};
  do
    createDirectory $dir
  done
}

cd "${HOME}"

: "Setup Dein vim" && {
  curl -s https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > "${HOME}/installer.sh"

  sh "${HOME}/installer.sh" "${BUNDLES_DIR}" > /dev/null

  rm -rf "${HOME}/installer.sh"
}

: "Clone and setup color themes" && {
  COLOR_REPOS=("https://github.com/cocopon/iceberg.vim.git" "https://github.com/sheerun/vim-wombat-scheme.git")

  cd "${THEME_DIR}"

  for repo in ${COLOR_REPOS[@]};
  do
    git clone $repo >/dev/null
  done

  for item in `ls ${THEME_DIR} | awk '{print $1}'`;
  do
    THEME_COLOR_DIR="${THEME_DIR}/${item}/colors"
    THEME_SRC_DIR="${THEME_DIR}/${item}/src"
    THEME_AUTOLOAD_DIR="${THEME_DIR}/${item}/autoload"

    if [ -d "${THEME_COLOR_DIR}" ];
    then
      findAndCp "${THEME_COLOR_DIR}" "${COLORS_DIR}"
    fi

    if [ -d "${THEME_SRC_DIR}" ];
    then
      findAndCp "${THEME_SRC_DIR}" "${SRC_DIR}"
    fi

    if [ -d "${THEME_AUTOLOAD_DIR}" ];
    then
      findAndCp "${THEME_AUTOLOAD_DIR}" "${AUTOLOAD_DIR}"
    fi
  done

  ln -s "${COLORS_DIR}" "${VIM_HOME}/"
}

: "Copy setting files" && {
  cd "${ROOT_DIR}"

  cp "${ROOT_DIR}/.vimrc" "${CONFIG_HOME}/.vimrc"
  cp dein.toml "${CONFIG_HOME}/dein.toml"
  cp dein_lazy.toml "${CONFIG_HOME}/dein_lazy.toml"

  ln -s "${CONFIG_HOME}/.vimrc" "${HOME}/.vimrc"
}

: "Initialization" && {
  if type expect > /dev/null 2>&1;
  then
    expect -c "
    spawn vim +:q
    expect \"Press ENTER or type command to continue\"
    send \"\n\"
    "
  fi
}
